syntax = "proto3";

package pb;

// Definindo o pacote
option go_package = "./pb";

// Definindo as mensagens
message Movie {
  int64 id = 1;
  string title = 2;
  string year = 3;
}

// Definindo os serviços
message GetMovieRequest {
  int64 id = 1;
}

message GetMovieResponse {
  Movie movie = 1;
}

message ListMoviesRequest {}

message ListMoviesResponse {
  repeated Movie movies = 1;
}

message CreateMovieRequest {
  int64 id = 1;
  string title = 2;
  string year = 3;
}

message CreateMovieResponse {
  Movie movie = 1;
}

message DeleteMovieRequest {
  int64 id = 1;
}

message DeleteMovieResponse {
  bool success = 1;
}

service MovieService {
  rpc GetMovie(GetMovieRequest) returns (GetMovieResponse);
  rpc ListMovies(ListMoviesRequest) returns (ListMoviesResponse);
  rpc CreateMovie(CreateMovieRequest) returns (CreateMovieResponse);
  rpc DeleteMovie(DeleteMovieRequest) returns (DeleteMovieResponse);
}